force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log {0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLog/tests/ErrorLogTest.cls
@isTest
private with sharing class ErrorLogTest {
    @TestSetup
    static void setup(){
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();

        for(Integer i = 0; i < 3; i++) {
            errorLogs.add(new Error_Log__c(Log_Date_Time__c = system.now(), 
                                           Process_Name__c = 'Process Name ' + i, 
                                           Log_Details__c = 'LogDetails ' + i));
        }

        insert(errorLogs);
    }

    @isTest
    static void insertErrorLogTest() {
        List<Error_Log__c> errorLogs = [SELECT Id FROM Error_Log__c];

        Test.startTest();
        Database.SaveResult[] results = Database.update(errorLogs);
        Test.stopTest();

        System.assertEquals(3, errorLogs.size());
        for (Database.SaveResult result: results) {
            System.assert(result.getErrors().isEmpty() == true);
            System.assertEquals(true, result.isSuccess());
        }
    }
}