force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Log {0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLog/ErrorLog.cls
public with sharing class ErrorLog {
    public static void insertErrorLog(String logProcessName) {
        Error_Log__c errorLog = new Error_Log__c();
        errorLog.Log_Date_Time__c = System.now();
        
        errorLog.Log_Details__c = ex.getStackTraceString() +
        '<br/> <strong> Mesage is </strong> ' + ex.getMessage() + 
        '<br/> ' + ex.getCause() +' <br/> '+ ex.getTypeName()+' <br/> '+ex.getLineNumber();

        errorLog.Process_Name__c = logProcessName;
        Database.insert(errorLog, false);
    }
}