force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event - Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DuplicateEventSpeakerHandler/DuplicateEventSpeakerHandler.cls
public with sharing class DuplicateEventSpeakerHandler {
    public static void duplicateEventSpeaker(List<Event_Speaker__c> eventSpeakerList) {

            Set<String> speakerSet = new Set<String>();
            for (Event_Speaker__c eventSpeaker: eventSpeakerList) {
                speakerSet.add(eventSpeaker.Speaker__c);
            }

            List<Event_Speaker__c> duplicateEventSpeakers = [SELECT Speaker__c FROM Event_Speaker__c WHERE Speaker__c IN: speakerSet];

            for (Event_Speaker__c eventSpeaker: eventSpeakerList) {
                if (duplicateEventSpeakers.size() != 0) {
                    eventSpeaker.Speaker__c.addError('This speaker is already assigned to the event.');
                } 
            }
            //ErrorLog.insertErrorLog(system.now(), 'Duplicate event speaker', 'Speaker can only be assigned to one event.')
            //gdziekolwiek bym to dał, nie wyswietla rekordow
    }
}