force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>Event {0}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event - Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event - Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventSpeakerListController/EventSpeakerListController.cls
public with sharing class EventSpeakerListController {
    public EventSpeakerListController() {

    }

    @AuraEnabled(cacheable = true)
    public static List<Event_Speaker__c> getEventSpeakers(Id eventRecordId) {
        List<Event_Speaker__c> organizersList = 
        [SELECT Id, Speaker__r.Id, Speaker__r.Name, Speaker__r.Phone__c, Speaker__r.Email__c, Event__r.Id 
        FROM Event_Speaker__c WHERE Event__r.Id =: eventRecordId];

        return organizersList;
    }
}